[file_locations]

#location of the algorithm files for stocks
stockAlgosDir = "./algos/"

#where the currently held stocks are stored and various info about them, as well as the cash returned by
posList = "../stockStuff/posListMulti.json"

#file containing the stocks to buy for the day
buyList = "../stockStuff/buyListMulti.json"

#where the API keys are stored
keyFile = "../stockStuff/apikeys/steve.txt"

#file containing the error tracebacks
errLog = "../stockStuff/multiStonkErr.txt"