version: '3.6'
services:
  multistock-stocks-api:
    image: multistock-api-server
    build:
      dockerfile: multistock-server/Dockerfile
    ports:
      - "2010:80"
    restart: always
    # This is to make sure that the container is always up-to-date
    container_name: multistock-server
  multistock-stocks:
    image: multistock-trading-bot
    build:
      dockerfile: Dockerfile.bot
    # ports:
    #   - ":80"
    restart: always
    # This is to make sure that the container is always up-to-date
    container_name: multistock-trading-bot
